### ISSUE TITLE
Unrecoverable error

### ISSUE THREAD

**Issue by karl0-dev** [devdot/dqol-resource-monitor#1]
Hello,

Just dropping this bug report, I installed monitor into my highly modded existing K2SE game, got error instantly.

`3721.784 Script @__stdlib__/stdlib/event/event.lua:284: Attempt to deregister already non-registered listener from event: -10
3902.078 Error MainLoop.cpp:1404: Exception at tick 105414621: The mod Resource Monitor (1.1.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event dqol-resource-monitor::on_gui_click (ID 1)
__dqol-resource-monitor__/components/ui/window.lua:115: attempt to index field 'titlebar' (a nil value)
stack traceback:
	__dqol-resource-monitor__/components/ui/window.lua:115: in function 'refreshTitle'
	__dqol-resource-monitor__/components/ui/site.lua:16: in function 'show'
	__dqol-resource-monitor__/components/ui/site.lua:177: in function '?'
	__dqol-resource-monitor__/components/ui/ui.lua:84: in function <__dqol-resource-monitor__/components/ui/ui.lua:70>
`

I can give you error log and save file if you want them

**Comment by devdot** [comment]
Hi @karl0-dev, thanks for your bug report! I wasn't able to reconstruct your bug but I spotted something in the code that might be the cause of this. If the issue persist in version 1.1.1 please let me know what mods you're using (or send me the save file).
